-- =========================================================================
-- BJJ ACADEMY SYSTEM - SQLITE EXPORT
-- Target: database/bjj_master.db
-- Generated: 2026-09-24T15:17:32.807Z
-- =========================================================================

PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

-- 1. MEMBERS (21 records)
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-kid-01', 'Yousef Al-Khatib', '2018-04-12', 'Kids', 'Grey-White', 2, 'class_pack', 5, 8, '2026-09-01', '2026-10-01', 'active', 34, '+962 79 901 0001', 'parent.khatib@example.com', 'Age 8 (Pee Wee Division). Very enthusiastic, loves armbar drills.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-kid-02', 'Maya Haddad', '2015-06-20', 'Kids', 'Yellow', 3, 'class_pack', 1, 12, '2026-08-28', '2026-09-28', 'warning', 88, '+962 79 902 0002', 'samira.haddad@example.com', 'Age 11 (Junior Division). Candidate for Orange-White belt test soon. Needs renewal!');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-kid-03', 'Zayd Qasim', '2020-08-15', 'Kids', 'White', 1, 'class_pack', 0, 8, '2026-08-20', '2026-09-20', 'expired', 16, '+962 79 903 0003', 'tariq.qasim@example.com', 'Age 6 (Mighty Mites). Finished 8-class punch card. Needs renewal reminder!');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-kid-04', 'Leen Nabulsi', '2017-02-14', 'Kids', 'Grey', 1, 'class_pack', 6, 8, '2026-09-10', '2026-10-10', 'active', 28, '+962 79 904 0004', 'parent.nabulsi@example.com', 'Age 9 (Pee Wee Division). Training with sister. Fast learner.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-kid-05', 'Omar Barakat', '2012-10-05', 'Kids', 'Orange', 2, 'monthly_unlimited', -1, -1, '2026-09-01', '2026-10-01', 'active', 142, '+962 79 905 0005', 'fadi.barakat@example.com', 'Age 14 (Teen Youth Division). Competed in National Cup. Excellent guard retention.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-kid-06', 'Talia Samer', '2019-03-10', 'Kids', 'Grey-White', 3, 'class_pack', 2, 8, '2026-08-25', '2026-09-25', 'warning', 44, '+962 79 906 1101', 'samer.parent@example.com', 'Age 7 (Pee Wee Division). 2 classes remaining. Ready for Grey belt promotion.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-kid-07', 'Adam Al-Khatib', '2016-07-22', 'Kids', 'Yellow-White', 1, 'class_pack', 4, 8, '2026-09-05', '2026-10-05', 'active', 52, '+962 79 907 2202', 'parent.khatib@example.com', 'Age 10 (Junior Division). Brother of Yousef. Excellent takedown defense.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-kid-08', 'Zein Mansour', '2021-09-01', 'Kids', 'White', 0, 'class_pack', 8, 8, '2026-09-20', '2026-10-20', 'active', 1, '+962 79 908 3303', 'mona.mansour@example.com', 'Age 5 (Mighty Mites). Brand new enrollment! First month on the mats.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-kid-09', 'Salma Jarar', '2014-11-15', 'Kids', 'Orange-White', 3, 'class_pack', 7, 12, '2026-09-02', '2026-10-02', 'active', 110, '+962 79 909 4404', 'parent.jarar@example.com', 'Age 12 (Junior Division). Youth tournament competitor, strong triangle choke setups.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-kid-10', 'Hashem Othman', '2011-05-30', 'Kids', 'Green-White', 2, 'class_pack', 0, 8, '2026-08-15', '2026-09-15', 'expired', 135, '+962 79 910 5505', 'othman.parent@example.com', 'Age 15 (Teen Youth Division). Transitioning soon to Juvenile Teens. Needs renewal.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-teen-01', 'Kareem Majali', '2009-03-25', 'Teens', 'Blue', 2, 'class_pack', 7, 12, '2026-09-05', '2026-10-05', 'active', 195, '+962 79 906 0006', 'kareem.majali@example.com', 'Age 17 (Juvenile Division). Converted from youth green belt to Juvenile Blue. Competitor.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-teen-02', 'Sara Al-Bitar', '2010-01-18', 'Teens', 'White', 3, 'class_pack', 2, 8, '2026-08-25', '2026-09-25', 'warning', 56, '+962 79 907 0007', 'sara.bitar@example.com', 'Age 16 (Juvenile Division). 2 classes remaining. Send reminder for renewal.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-teen-03', 'Faris Qasim', '2009-08-14', 'Teens', 'Blue', 1, 'class_pack', 0, 12, '2026-08-10', '2026-09-10', 'expired', 88, '+962 79 908 6606', 'faris.qasim@example.com', 'Age 17 (Juvenile Division). 0 classes left. Prompt for renewal at front desk.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-teen-04', 'Rayan Suboh', '2010-06-02', 'Teens', 'White', 4, 'monthly_unlimited', -1, -1, '2026-09-01', '2026-10-01', 'active', 75, '+962 79 909 7707', 'rayan.suboh@example.com', 'Age 16 (Juvenile Division). 4 stripes White Belt, ready for Blue Belt test.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-adult-01', 'Ahmad Al-Saleh', '2000-05-14', 'Adults', 'Blue', 3, 'monthly_unlimited', -1, -1, '2026-09-01', '2026-10-01', 'active', 210, '+962 79 908 0008', 'ahmad.saleh@example.com', 'Age 26 (Adults Division). Consistent attendance 4x/week. Strong half-guard player.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-adult-02', 'Hamza Dajani', '1995-11-03', 'Adults', 'Purple', 1, 'class_pack', 8, 12, '2026-09-08', '2026-10-08', 'active', 340, '+962 79 909 0009', 'hamza.dajani@example.com', 'Age 31 (Master 1 Division). Experienced leg-locker. Regular attendee in morning sessions.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-adult-03', 'Tariq Mansour', '2002-09-08', 'Adults', 'White', 2, 'class_pack', 1, 8, '2026-08-27', '2026-09-27', 'warning', 31, '+962 79 910 0010', 'tariq.mansour@example.com', 'Age 24 (Adults Division). 1 class left in current package. High renewal probability.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-adult-04', 'Laila Al-Zubi', '1998-01-19', 'Adults', 'Blue', 2, 'class_pack', 6, 8, '2026-09-12', '2026-10-12', 'active', 120, '+962 79 911 8811', 'laila.zubi@example.com', 'Age 28 (Adults Division). Strong guard passer and back-take specialist.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-adult-05', 'Yazan Nabulsi', '1991-04-12', 'Adults', 'Purple', 3, 'class_pack', 0, 12, '2026-08-14', '2026-09-14', 'expired', 280, '+962 79 912 9912', 'yazan.nabulsi@example.com', 'Age 35 (Master 2 Division). Finished 12-class punch card. Needs renewal.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-adult-06', 'Mustafa Al-Kurd', '1997-12-05', 'Adults', 'Brown', 1, 'monthly_unlimited', -1, -1, '2026-09-01', '2026-10-01', 'active', 510, '+962 79 913 1122', 'mustafa.kurd@example.com', 'Age 29 (Adults Division). Brown belt competitor, assists with evening sparring rounds.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-adult-07', 'Rami Haddad', '1984-08-20', 'Adults', 'Black', 1, 'monthly_unlimited', -1, -1, '2026-09-01', '2026-10-01', 'active', 620, '+962 79 914 2233', 'rami.haddad@example.com', 'Age 42 (Master 3 Division). Veteran Black Belt practitioner and honorary member.');

COMMIT;
