-- =========================================================================
-- BJJ ACADEMY SYSTEM - SQLITE EXPORT
-- Target: database/bjj_master.db
-- Generated: 2026-09-28T19:53:38.603Z
-- =========================================================================

PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

-- 1. MEMBERS (20 records)
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-kid-01', 'Yousef Al-Khatib', '2018-04-12', 'Kids', 'Grey-White', 2, 'class_pack', 5, 8, '2026-09-01', '2026-10-01', 'active', 34, '+962 79 901 0001', 'parent.khatib@example.com', 'Age 8 (Pee Wee Division). Very enthusiastic, loves armbar drills.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-kid-02', 'Maya Haddad', '2015-06-20', 'Kids', 'Yellow', 3, 'class_pack', 1, 12, '2026-08-28', '2026-09-28', 'warning', 88, '+962 79 902 0002', 'samira.haddad@example.com', 'Age 11 (Junior Division). Candidate for Orange-White belt test soon. Needs renewal!');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-kid-03', 'Zayd Qasim', '2020-08-15', 'Kids', 'White', 1, 'class_pack', 0, 8, '2026-08-20', '2026-09-20', 'expired', 16, '+962 79 903 0003', 'tariq.qasim@example.com', 'Age 6 (Mighty Mites). Finished 8-class punch card. Needs renewal reminder!');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-kid-04', 'Layla Nabulsi', '2013-09-10', 'Kids', 'Orange-White', 2, 'monthly_unlimited', -1, -1, '2026-09-01', '2026-10-01', 'active', 120, '+962 79 904 0004', 'nabulsi.family@example.com', 'Age 13 (Teen Prep). Unmetered monthly pass. High technical consistency.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-kid-05', 'Kareem Bitar', '2011-10-15', 'Kids', 'Orange-Black', 3, 'class_pack', 7, 12, '2026-09-10', '2026-10-10', 'active', 145, '+962 79 905 0005', 'ziad.bitar@example.com', 'Age 15 (Approaching 16 - upcoming IBJJF Teen promotion transition candidate).');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-kid-06', 'Sarah Khoury', '2017-02-28', 'Kids', 'Grey', 1, 'class_pack', 4, 8, '2026-09-05', '2026-10-05', 'active', 42, '+962 79 906 0006', 'khoury.parents@example.com', 'Age 9 (Pee Wee Division). Excellent guard retention skills.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-teen-01', 'Rayan Al-Masri', '2010-03-14', 'Teens', 'Green', 3, 'class_pack', 8, 12, '2026-09-01', '2026-10-01', 'active', 190, '+962 79 911 0001', 'rayan.masri@example.com', 'Age 16 (Juvenile 1 Division). IBJJF National Championship competitor.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-teen-02', 'Jad Tannous', '2010-07-22', 'Teens', 'Blue', 1, 'class_pack', 2, 12, '2026-08-30', '2026-09-30', 'warning', 210, '+962 79 912 0002', 'jad.tannous@example.com', 'Age 16 (Juvenile Blue Belt). Fast guard passer. Renewal due shortly.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-teen-03', 'Yasmeen Dajani', '2009-05-18', 'Teens', 'Green-White', 2, 'class_pack', 0, 8, '2026-08-15', '2026-09-15', 'expired', 75, '+962 79 913 0003', 'yasmeen.dajani@example.com', 'Age 17 (Juvenile 2 Division). Finished pack, needs renewal!');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-teen-04', 'Hamza Saleh', '2009-11-05', 'Teens', 'Blue', 2, 'monthly_unlimited', -1, -1, '2026-09-01', '2026-10-01', 'active', 230, '+962 79 914 0004', 'hamza.saleh@example.com', 'Age 17. Dedicated juvenile athlete preparing for adult division next year.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-adult-01', 'Ahmad Al-Zoubi', '2000-08-14', 'Adults', 'White', 2, 'class_pack', 5, 8, '2026-09-01', '2026-10-01', 'active', 48, '+962 79 921 0001', 'ahmad.zoubi@example.com', 'Adult fundamentals student. Regular at 7:30 PM evening classes.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-adult-02', 'Rami Al-Husseini', '1995-03-22', 'Adults', 'White', 4, 'class_pack', 1, 12, '2026-08-25', '2026-09-25', 'warning', 112, '+962 79 922 0002', 'rami.husseini@example.com', 'Adult 4-stripe white belt. Preparing for Blue Belt grading test. Needs renewal!');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-adult-03', 'Faisal Majali', '1997-12-05', 'Adults', 'Blue', 2, 'class_pack', 9, 12, '2026-09-15', '2026-10-15', 'active', 160, '+962 79 923 0003', 'faisal.majali@example.com', 'Adult Blue belt. Active in both Gi and No-Gi sparring.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-adult-04', 'Daniel Nassar', '1992-09-18', 'Adults', 'Blue', 3, 'monthly_unlimited', -1, -1, '2026-09-01', '2026-10-01', 'active', 280, '+962 79 924 0004', 'daniel.nassar@example.com', 'Unlimited monthly pass. Trains 4-5 times a week.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-adult-05', 'Tariq Mansour', '1998-04-30', 'Adults', 'Purple', 2, 'class_pack', 6, 12, '2026-09-05', '2026-10-05', 'active', 360, '+962 79 925 0005', 'tariq.mansour@example.com', 'Purple belt competitor. Strong open guard and berimbolo attacks.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-adult-06', 'Bilal Obeidat', '1988-02-14', 'Adults', 'Purple', 4, 'class_pack', 0, 8, '2026-08-10', '2026-09-10', 'expired', 410, '+962 79 926 0006', 'bilal.obeidat@example.com', 'Adult Master 2 purple belt. Package finished. Needs top-up.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-adult-07', 'Sami Qureishi', '1984-06-11', 'Adults', 'Brown', 1, 'monthly_unlimited', -1, -1, '2026-09-01', '2026-10-01', 'active', 580, '+962 79 927 0007', 'sami.qureishi@example.com', 'Senior Brown belt practitioner & sparring mentor.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-adult-08', 'Hani Shaker', '1990-11-20', 'Adults', 'Black', 1, 'monthly_unlimited', -1, -1, '2026-09-01', '2026-10-01', 'active', 720, '+962 79 928 0008', 'hani.shaker@example.com', 'Visiting black belt practitioner & master team member.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-vip-01', 'Dr. Marwan Kawar', '1981-05-14', 'Adults', 'Blue', 1, 'class_pack', 3, 5, '2026-09-10', '2026-11-10', 'active', 22, '+962 79 931 0001', 'dr.marwan@kawarclinic.com', 'VIP 1-on-1 private student with Head Professor Lucas Silva. Focuses on safe pressure passing.');
INSERT OR REPLACE INTO members (id, full_name, birth_date, age_group, belt_rank, stripes, membership_type, classes_remaining, classes_total, membership_start_date, membership_end_date, status, total_classes_attended, phone, email, notes) VALUES ('mem-vip-02', 'Nasser Al-Sabah', '1987-03-09', 'Adults', 'Purple', 1, 'class_pack', 7, 10, '2026-09-01', '2026-11-01', 'active', 38, '+962 79 932 0002', 'nasser.sabah@investment.com', 'VIP private grappling training with Coach Tariq Ziad.');

COMMIT;
